package com.globalpaymentsinc.greenhouse;

import org.apache.commons.lang.StringUtils;

/**
 * DETAIL RESPONSE RECORD, TYPE 05
 * 
 * @author nickfeng
 *
 */
public class BDetailResponse {

	/**
	 * Record Type, 1-2, AN 2, Always 05.
	 */
	private String recordType = "05";

	/**
	 * Sales Type, 3-3, N 1, Valid codes are:
	 * <ul>
	 * <li>0 - Sale/Purchase</li>
	 * <li>1 - Cash Advance</li>
	 * <li>2 - Mail/Telephone Order</li>
	 * <li>7 - Credit/Return</li>
	 * </ul>
	 */
	private char salesType;

	/**
	 * Account Number, 4-22, AN 19, Cardholder's Account Number. Left justified,
	 * space filled.
	 */
	private String accountNumber;

	/* Filler, 3-3, AN 1, Space filled. */

	/**
	 * Transaction Amount, 28-37, N 10, Total amount of the transaction, includes
	 * any amount in the Amount 2 field. Right justified, zero filled. Decimal
	 * places based on transaction currency.
	 */
	private String transactionAmount;

	/**
	 * Transaction Date, 38-43, N 6, MMDDYY format. Local date.
	 */
	private String transactionDate;

	/**
	 * Reference Number, 44-62, AN 19, Optional unique reference number used for
	 * research. This is the value supplied in either Market Data or the Detail
	 * Request Record. If not supplied in the file, the Reference Number will be
	 * generated by Global Payments.
	 */
	private String referenceNumber;

	/**
	 * Action Code, 63-65, AN 3, Code identifying Global Payments’ response.
	 */
	private String actionCode;

	/**
	 * Verbiage, 66-81, AN 16, Verbiage associated with the Action Code.
	 */
	private String verbiage;

	/* Filler, 82-94, AN 13, Space filled. */

	/**
	 * Record Sequence Number, 95-100, N 6, Sequence number of the previous record
	 * plus 1.
	 */
	private String recordSequenceNumber;

	public String getRecordType() {
		return recordType;
	}

	public void setRecordType(String recordType) {
		this.recordType = recordType;
	}

	public char getSalesType() {
		return salesType;
	}

	public void setSalesType(char salesType) {
		this.salesType = salesType;
	}

	public String getAccountNumber() {
		return accountNumber;
	}

	public void setAccountNumber(String accountNumber) {
		this.accountNumber = accountNumber;
	}

	public String getTransactionAmount() {
		return transactionAmount;
	}

	public void setTransactionAmount(String transactionAmount) {
		this.transactionAmount = transactionAmount;
	}

	public String getTransactionDate() {
		return transactionDate;
	}

	public void setTransactionDate(String transactionDate) {
		this.transactionDate = transactionDate;
	}

	public String getReferenceNumber() {
		return referenceNumber;
	}

	public void setReferenceNumber(String referenceNumber) {
		this.referenceNumber = referenceNumber;
	}

	public String getActionCode() {
		return actionCode;
	}

	public void setActionCode(String actionCode) {
		this.actionCode = actionCode;
	}

	public String getVerbiage() {
		return verbiage;
	}

	public void setVerbiage(String verbiage) {
		this.verbiage = verbiage;
	}

	public String getRecordSequenceNumber() {
		return recordSequenceNumber;
	}

	public void setRecordSequenceNumber(String recordSequenceNumber) {
		this.recordSequenceNumber = recordSequenceNumber;
	}

	@Override
	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append(recordType);
		sb.append(salesType);
		sb.append(StringUtils.rightPad(accountNumber, 19, ' '));
		sb.append(StringUtils.repeat(" ", 5));
		sb.append(StringUtils.leftPad(transactionAmount, 10, '0'));
		sb.append(transactionDate);
		sb.append(referenceNumber);
		sb.append(actionCode);
		sb.append(verbiage);
		sb.append(StringUtils.repeat(" ", 13));
		sb.append(StringUtils.leftPad(recordSequenceNumber, 6, '0'));
		return sb.toString();
	}

	public static BDetailResponse fromString(String s) {
		if (StringUtils.isEmpty(s) || s.length() != 100 || !s.startsWith("05")) {
			return null;
		}
		BDetailResponse bdr = new BDetailResponse();
		bdr.setSalesType(s.charAt(2));
		bdr.setAccountNumber(s.substring(3, 22));
		bdr.setTransactionAmount(s.substring(27, 37));
		bdr.setTransactionDate(s.substring(37, 43));
		bdr.setReferenceNumber(s.substring(43, 62));
		bdr.setActionCode(s.substring(62, 65));
		bdr.setVerbiage(s.substring(65, 81));
		bdr.setRecordSequenceNumber(s.substring(94, 100));
		return bdr;
	}

}
